paths:
  data: data
  collections: content
  includes: layouts
  layouts: layouts
  static: static
  uploads: static/uploads
  source: ''
  archetypes: archetypes
  assets: assets
  content: content
  pages: content
  publish: public
  config: ''
collections_config:
  pages:
    path: content
    output: true
    filter: strict
    parse_branch_index: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  deutsch:
    path: content/deutsch
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  english:
    path: content/english
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  french:
    path: content/french
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  posts:
    path: content/posts
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  romanian:
    path: content/romanian
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
base_url: /
timezone: Etc/UTC
