---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Homepage
- type: document
  path: content/english/_index.yml
  label: Homepage (en)
- type: document
  path: content/deutsch/_index.md
  label: Homepage (de)
- type: document
  path: content/french/_index.md
  label: Homepage (fr)
- type: document
  path: content/romanian/_index.md
  label: Homepage (ro)
- type: heading
  label: Blog
- type: document
  path: content/english/blog/_index.md
  label: Blog Page (en)
- type: document
  path: content/deutsch/blog/_index.md
  label: Blog Page (de)
- type: document
  path: content/french/blog/_index.md
  label: Blog Page (fr)
- type: document
  path: content/romanian/blog/_index.md
  label: Blog Page (ro)
- type: directory
  path: content/english/blog
  label: Blog Post (en)
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - post
- type: directory
  path: content/deutsch/blog
  label: Blog Post (de)
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - post
- type: directory
  path: content/french/blog
  label: Blog Post (fr)
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - post
- type: directory
  path: content/romanian/blog
  label: Blog Post (ro)
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - post
- type: heading
  label: Others Page
- type: document
  path: content/english/contact/_index.md
  label: Contact (en)
- type: document
  path: content/deutsch/contact/_index.md
  label: Contact (de)
- type: document
  path: content/french/contact/_index.md
  label: Contact (fr)
- type: document
  path: content/romanian/contact/_index.md
  label: Contact (ro)
- type: document
  path: content/english/pricing/_index.md
  label: Pricing (en)
- type: document
  path: content/deutsch/pricing/_index.md
  label: Pricing (de)
- type: document
  path: content/french/pricing/_index.md
  label: Pricing (fr)
- type: document
  path: content/romanian/pricing/_index.md
  label: Pricing (ro)
- type: document
  path: content/english/faq/_index.md
  label: FAQ (en)
- type: document
  path: content/deutsch/faq/_index.md
  label: FAQ (de)
- type: document
  path: content/french/faq/_index.md
  label: FAQ (fr)
- type: document
  path: content/romanian/faq/_index.md
  label: FAQ (ro)
- type: heading
  label: All Pages
- type: directory
  path: content
  label: All Pages
  create: all
  match: "**/*"
  exclude: _index.md
  templates:
  - new-page
- type: heading
  label: Configuration
- type: document
  path: config/_default/config.toml
  label: Configuration
- type: document
  path: config/_default/params.toml
  label: Parameters
- type: document
  path: config.toml
  label: Variables & Plugins
- type: document
  path: config/_default/languages.toml
  label: Languages
- type: document
  path: config/_default/menus.en.toml
  label: Menu (en)
- type: document
  path: config/_default/menus.de.toml
  label: Menu (de)
- type: document
  path: config/_default/menus.fr.toml
  label: Menu (fr)
- type: document
  path: config/_default/menus.ro.toml
  label: Menu (ro)
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
